output-format: text

strictness: medium
test-warnings: true
doc-warnings: false

ignore-paths:
  - docs
  - tests
  - venv

uses:
  - flask
  - celery

pylint:
  disable:
    - import-error

bandit:
  run: true

dodgy:
  run: true